In [2]:
#!pip install numpy

In [3]:
import numpy as np


In [4]:
# tao mang
a = np.array([1,2,3])

# in mang
print(a)

# in phan tu thu 1
element = a[1]
print(element)

[1 2 3]
2


In [5]:
# tao mang 2 chieu
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix: ", matrix)

# in mot phan tu
element = matrix[1, 2]
print(element)

Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [10]:
# Cach tao mang
# tao mang toan la so 0
a = np.zeros(5)
print(a)

# tao mang toan la so 1
a = np.ones(5)
print(a)

# tao mang
a = np.empty(5)
print(a)

# tao mang tu 0 den 100
a = np.arange(100)
print(a)

# tao mang gom cac phan tu voi khoang cach deu nhau
a = np.linspace(0, 10, num = 5)
print(a)

# xac dinh kieu du lieu
a = np.ones(5, dtype = np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.   2.5  5.   7.5 10. ]


array([1, 1, 1, 1, 1], dtype=int64)

In [11]:
# them, xoa, sap xep mang

# tao mang ban dau
arr = np.array([3, 1, 2, 4, 5])
print(arr)

# sap xep
arr = np.sort(arr)
print(arr)

# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)

# them phan tu vao mang
arr = np.append(arr, 100)
print(arr)

# xoa di mot vi tri nao do trong mang
arr = np.delete(arr, 3)
print(arr)

[3 1 2 4 5]
[1 2 3 4 5]
[5 4 3 2 1]
[  5   4   3   2   1 100]
[  5   4   3   1 100]


In [12]:
# tao mot mang 2 
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

# tang dan theo hang
sap_xep_theo_hang = np.sort(arr, axis=1) 
print(sap_xep_theo_hang)

# tang dan theo cot
sap_xep_theo_cot = np.sort(arr, axis=0) 
print(sap_xep_theo_cot)

[[1 2 3]
 [4 6 8]
 [5 7 9]]
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [13]:
# tao mot mang 2 
arr = np.array([[3, 1, 2],
                [4, 6, 8],
                [9, 7, 5]])

# tang dan theo hang
sap_xep_theo_hang = -np.sort(-arr, axis=1) 
print(sap_xep_theo_hang)

# tang dan theo cot
sap_xep_theo_cot = -np.sort(-arr, axis=0) 
print(sap_xep_theo_cot)

[[3 2 1]
 [8 6 4]
 [9 7 5]]
[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [14]:
# tao mot mang 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# su dung cac thuoc tinh de lay thong tin ve mang
# so chieu (2 chiều)
so_chieu = arr.ndim
# kich thuoc (tong so phan tu, 6)
kich_thuoc = arr.size
# hinh dang (so hang x so cot, (2, 3))
hinh_dang = arr.shape

print("So chieu:", so_chieu)
print("Kich thuoc:", kich_thuoc)
print("Hinh dang:", hinh_dang)

So chieu: 2
Kich thuoc: 6
Hinh dang: (2, 3)


In [15]:
# chuyen doi kieu du lieu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [16]:
# thay doi hinh dang cua mang
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [17]:
# chuyen thanh mang 1 chieu
reshaped_arr = reshaped_arr.flatten() 
print(reshaped_arr)

[1 2 3 4 5 6]


In [18]:
# cat lat mang
arr = np.array([1, 2, 3, 4, 5])

# cat tu phan tu 1 den 4
sub_arr = arr[1:4]  
print(sub_arr)

sub_arr = arr[:-1] 
print(sub_arr)

sub_arr = arr[-2:] 
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [19]:
# chuyen vi mang
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

# de chuyen vi mang, chung ta co the su dung .T hoac ham numpy.tránpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# noi mang
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [21]:
# ham tinh tong (sum)
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tong cua mang arr:", total)

# ham tinh trung binh (mean)
average = np.mean(arr)
print("Gia tri trung binh cua mang arr:", average)

# ham tinh gia tri lon nhat va nho nhat (max và min)
max_value = np.max(arr)
min_value = np.min(arr)
print("Gia tri lon nhat trong mang arr:", max_value)
print("Gia tri nho nhat trong mang arr:", min_value)

# ham tinh do lech chuan (standard deviation)
std_deviation = np.std(arr)
print("Do lech chuan cua mang arr:", std_deviation)

# ham tinh phuong sai (variance)
variance = np.var(arr)
print("Phuong sai cua mang arr:", variance)

# ham tinh tong tich chap (dot product)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tong tich chap cua arr1 va arr2:", dot_product)

Tong cua mang arr: 15
Gia tri trung binh cua mang arr: 3.0
Gia tri lon nhat trong mang arr: 5
Gia tri nho nhat trong mang arr: 1
Do lech chuan cua mang arr: 1.4142135623730951
Phuong sai cua mang arr: 2.0
Tong tich chap cua arr1 va arr2: 32
